/**
 * This file is generated by generate-i18n.mjs
 * Do not edit this file directly
 */
import type enMessage from '../locales/en/messages.json';
import type jaMessage from '../locales/ja/messages.json';
import type koMessage from '../locales/ko/messages.json';
import type zh_CNMessage from '../locales/zh_CN/messages.json';
import type zh_TWMessage from '../locales/zh_TW/messages.json';

export type MessageKey = keyof typeof enMessage &
  keyof typeof jaMessage &
  keyof typeof koMessage &
  keyof typeof zh_CNMessage &
  keyof typeof zh_TWMessage;

export type DevLocale = 'en' | 'ja' | 'ko' | 'zh_CN' | 'zh_TW';
